openapi: 3.0.1

info:
  title: Job serf API
  version: 1.0.0

servers:
  - url: /
    description: localhost

paths:
  /set-up-search-config:
    post:
      security:
        - HubApiKeyAuth: []
      summary: Set up search config
      tags:
        - SearchConfig
      operationId: createSearchConfig
      requestBody:
        $ref: '#/components/requestBodies/newConfig'
      responses:
        201:
          $ref: '#/components/responses/genericResponse'
        400:
          $ref: '#/components/responses/error'
        500:
          $ref: '#/components/responses/error'

components:
  schemas:
    uuid:
      type: string
      format: uuid

    email:
      type: string
      format: email

    url:
      type: string

    searchString:
      type: string
      minLength: 0
      maxLength: 128

    category:
      type: string
      enum:
        - javascript
        - ux

    seniority:
      type: string
      enum:
        - senior
        - mid
        - junior
        - expert

    seniorityArray:
      type: array
      items:
        $ref: '#/components/schemas/seniority'

    companyRating:
      type: number
      format: float
      minimum: 1
      maximum: 5

  parameters:
    clientID:
      name: clientID
      in: path
      schema:
        $ref: '#/components/schemas/uuid'
      required: true

  requestBodies:
    newConfig:
      description: Create new client
      content:
        application/json:
          schema:
            type: object
            properties:
              searchString:
                $ref: '#/components/schemas/searchString'
              category:
                $ref: '#/components/schemas/category'
              seniority:
                $ref: '#/components/schemas/seniorityArray'
              companyRating:
                $ref: '#/components/schemas/companyRating'
            required:
              - category
              - seniority
              - companyRating
            additionalProperties: false

  responses:
    genericResponse:
      description: Generic successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                format: int32
              message:
                type: string
                maxLength: 1024
            required:
              - status
              - message
            additionalProperties: false
    error:
      description: Generic error response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                format: int32
              message:
                type: string
                maxLength: 1024
              data:
                type: object
            required:
              - status
              - message
            additionalProperties: false